const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        sans: ["Nanito", ...defaultTheme.fontFamily.sans],
        plume: ["Plume"],
        lemon: ["Lemon"],
      },
      backgroundImage: {
        mary: "url('./photos/Mary.png')",
        yly: "url('./photos/Yly.png')",
        angelina: "url(./photos/Angelina.png)",
      },
    },
    fontSize: {
      xs: ".3rem",
      sm: ".6rem",
      basic: ".8rem",
      special: "0.9rem",
      base: "1rem",
      title: "1.2rem",
      info: "1.4rem",
      titleD: "3.2rem",
      baseD: "1.3rem",
      basicD: "1rem",
      infoD: "1.6rem",
      bigTitleD: "6.4rem",
    },
    spacing: {
      none: "0",
      s01: "0.1rem",
      s03: "0.3rem",
      s05: "0.5rem",
      s1: "1rem",
      s1h: "1.5",
      s2: "2rem",
      s3: "3rem",
      s4: "4rem",
      s7: "7rem",
      s9: "9rem",
      s10: "10rem",
      s11: "11rem",
      s14: "14rem",
      s20: "20rem",
      s30: "32rem",
      sp20: "20%",
      sp5: "50%",
      sp7: "70%",
      sp9: "90%",
      special: "0.6864999999999999rem",
      avatar: "6.25rem",
      avatarD: "10rem",
    },
    colors: {
      peach: "#F8CA9D",
      jusyPeach: "#FA6E4F",
      blue: "#2F327D",
      orange: "#F48C06",
      ocean: "#65DAFF",
      white: "#FFFFFF",
      text: "#696984",
      black: "#000000",
      gray: "#F2F2F2",
      purpure: "#F3627C",
      fox: "#FF6700",
      cookie: "#4F5052",
    },
    backgroundColor: (theme) => ({
      ...theme("colors"),
      primary: "#F8CA9D",
      secondary: "#F2F2F2",
    }),
    gradientColorStops: (theme) => ({
      ...theme("colors"),
      primary: "#F8CA9D",
      secondary: "#ffed4a",
    }),
    borderRadius: {
      flag: "0.2rem",
      button: "0.4rem",
      flagD: "0.8rem",
      bg: "3.5rem",
      frame: "1rem",
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
